language: csharp  
sudo: required  
dist: xenial  
mono: none
dotnet: 2.2.300
before_script:
  - dotnet restore
script:  
  - dotnet test ./ServicesAccessibilityChecker\AccessibilityChecker.Test\AccessibilityChecker.Test.csproj -f netcoreapp2.2