language: csharp  
sudo: required  
dist: xenial  
mono: none
dotnet: 2.2.300
before_script:
  - dotnet restore
script:  
  - dotnet test ./AccessibilityChecker.Test/AccessibilityChecker.Test.csproj -c Debug -f netcoreapp2.2